### ISSUE TITLE
Firmware upgrades fails for old OSTC Sport

### ISSUE THREAD

**Issue by glance-** [libdivecomputer/libdivecomputer#19]
In 9e92381be48866f3f13a11e98d59962575bb5ad3 which command to send the new firmware blob with was changed. I tried to upgrade a OSTC Sport with 10.53 to current 10.68 and it errored out with Unsupported command to S_BLOCK_WRITE2(0x31).

So, the check if to use S_BLOCK_WRITE or S_BLOCK_WRITE2 needs to take old hwOS Sport into account to. I don't know in which hwOS Sport version S_BLOCK_WRITE2 was added but it's there in 10.68 but absent in 10.53.

**Comment by jefdriesen** [comment]
To fix this, we first need to know in which Sport firmware version the new S_BLOCK_WRITE2 command was added. I already asked HW. And then we'll also need some way to tell apart the hwOS Tech from the Sport firmware. Because doing a simple `if (firmware >= 3.09 || firmware >= 10.X)` is of course not going to work. I'll need to check the documentation again.

Worst case scenario we can base the detection on the major number being in either the 3.X or 10.X range, and invert the condition to avoid trouble with future firmware versions (e.g. 4.X and 11.X):

 `if ((firmware < 3.09) || (firmware == 10.X && firmware < 10.X))`

**Comment by glance-** [comment]
We can either look at the high bits to decide if the firmware version is a "Sport" or a "Tech" firmware:
`if ( ( ( firmware & 0xff00 == 3) && (firmware & 0x00ff >= 0 ) ) || ( (firmware & 0xff00 == 10) && firmware & 0x00ff >= 64 ) )`

I have some memory that it's available as a flag in one of the descriptors. I don't have the protocol documentation available right now so I can't check.

**Comment by jefdriesen** [comment]
Fixed in commit fba5676b78f14c7d6cb79b48f264e74fd12c1f28
