### ISSUE TITLE
Mares Puck pro (and others of same family?): Salinity in xml export missing

### ISSUE THREAD

**Issue by h3llra1ser** [libdivecomputer/libdivecomputer#23]
`<salinity type="1">0.0</salinity>`
type 0 = fresh water
type 1 = salt water
the salinity is detected and marked in the type attribute, but the salinity value is zero.
I only know the Mares Puck Pro - perhaps even if the correct value is missing there should be set a "average" saline level?
(puck pro has no sensor and does only let you choose between fresh and salt water)

**Comment by jefdriesen** [comment]
I'm not aware of any dive computer being able to measure the salinity. It's only a user setting. (Decompression calculations are done using pressure, so it doesn't matter there.) A few dive computers also allow to configure the actual density (or have their internal values documented), rather than the simple salt/fresh water flag, and in that case we report it. Otherwise the (optional) density field is set to zero. An application can detect this and use some average value if necessary, but it's not libdivecomputer's job to fill in information that's not there.

For the xml output, maybe something like this would have been clearer:
`<salinity density="0.0">salt|fresh</salinity>`

**Comment by jefdriesen** [comment]
Closing the ticket because the density value is optional. The salinity in the xml output has been changed in commit 9b7aa813e0a9291b10e370847c139d19bb4c57b0.
